apiVersion: apps/v1
kind: Deployment
metadata:
  name: myngx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        nodename: a1
      containers:
        - name: nginxtest
          image: nginx:alpine
          # 只有镜像不存在时进行镜像拉取
          imagePullPolicy: IfNotPresent
          ports:
            # Pod 端口
            - containerPort: 80
