apiVersion: v1
kind: Secret
metadata:
  name: testcm
  namespace: test
  labels:
    cm: testcm
type: Opaque
data:
  db_name: dGVzdGRiMgo=
  db_host: MTI3LjAuMC4yCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: test2
  namespace: test
  labels:
    app: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      tty: true
      env:
        - name: db_name_new
          valueFrom:
            secretKeyRef:
              name: testcm
              key: db_name
      envFrom:
        - secretRef:
            name: testcm