apiVersion: v1
kind: Pod

metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox

spec:
#  nodeName: node02
  nodeSelector:
    "kubernetes.io/hostname": "node01"
  containers:
    - name: busybox
      image: busybox
