apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
spec:
  volumes: #定义pod的 存储卷
    - name: cm-vol
      configMap:
        name: info
    - name: sec-vol
      secret:
        secretName: user
  containers:
    - volumeMounts:
        - mountPath: /tmp/cm-items
          name: cm-vol        # 使用pod名为cm-vol的存储卷
        - mountPath: /tmp/sec-items
          name: sec-vol        # 使用pod名为sec-vol 的存储卷
      image: busybox
      name: busy
      imagePullPolicy: IfNotPresent
      command: ["/bin/sleep", "300"]
