apiVersion: v1
kind: Secret
metadata:
  name: testsec
  namespace: test
  labels:
    secret: testsec
type: Opaque
data:
  db_name: dGVzdGRiMgo=
  db_host: MTI3LjAuMC4yCg==
---
# 将configMap的所有的数据挂载到pod的容器内
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox
spec:
  nodeName: node01
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: workdir
      secret:
        secretName: testsec
        optional: true