#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: nfs-pv01
#  namespace: test
#  labels:
#    pv: nfs-pv01
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  #Recycle 删除Pvc同步删除PV | Retain
#  persistentVolumeReclaimPolicy: Recycle
#  nfs:
#    path: /nfs/share/pv01
#    server: 192.168.1.16
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  namespace: test
provisioner: cluster.local/nfs-subdir-external-provisioner
#parameters:
#  server: nfs-server.example.com
#  path: /share
#  readOnly: "false"
mountOptions:
  - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc02
  namespace: test
  labels:
    pvc: nfs-pvc02
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
#  selector:
#    matchLabels:
#      pv: nfs-pv01
---
# 将configMap的所有的数据挂载到pod的容器内
apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: test
  labels:
    app: web
spec:
  nodeName: node01
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: workdir
      persistentVolumeClaim:
        claimName: nfs-pvc02