# 将configMap的所有的数据挂载到pod的容器内
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox
spec:
  nodeName: node01
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
          # key 作为文件名 里面是值
  volumes:
    - name: workdir
      configMap:
        name: testcm
        optional: true # 没有这个configmap也能起来
