# 将pod的定义信息（metadata信息）挂载到容器内
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox
spec:
  nodeName: node01
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
              # podIP nodeIP sa
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: workdir
      downwardAPI:
        items:
          - path: podname.html
            fieldRef:
              fieldPath: metadata.name