apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: test
  labels: 
    app: busybox
spec: 
  containers:
  - name: busybox
    image: busybox
    #可选值： Always|IfNotPresent|Never
    imagePullPolicy: IfNotPresent
    #环境变量
    env: 
    - name: app
      value: busybox
    #运行终端
    tty: true
    #特权模式 对宿主机有root权限
    securityContext:
      privileged: true
    #工作目录
    workingDir: /test
    #命令
    command: ["/bin/sh"]
    #参数
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        memory: "100Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "200m"
