apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
  labels: 
    app: nginx
spec: 
  #可选值： Always|OnFailure|Never
  restartPolicy: Always
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    #卷挂载目录
    volumeMounts: 
    - name: cache-volume
      mountPath: /test/cache
  #定义卷
  volumes: 
  - name: cache-volume
    emptyDir: {}
