apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness
  namespace: test
spec:
  imagePullSecrets: 
  - name: regcred
  containers:
  - name: liveness
    image: harbor.kubeimooc.com/kubeimooc/liveness
    #每隔3s向容器探测，是否正常
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
