apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: dev
  labels:
    app: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      imagePullPolicy: IfNotPresent
      env:
      - name: app
        value: busybox
      # 终端
      tty: true
      # 拥有宿主机权限
      securityContext:
       privileged: true
      workingDir: /test
      command: ["/bin/sh"]
      args: ["-c","while true; do echo hello;sleep 10; done"]
      resources:
        requests:
          # 100mb
          memory: "100Mi"
          # 1核心 = 1000m
          cpu: "1000m"
        limits:
          memory: "200Mi"
          cpu: "1000m"

