apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
spec:
  # hostNetwork: true
  # 可选值  Default|ClusterFirst|ClusterFirstWithHostNet|None
  dnsPolicy: "Default"
  # dns配置
  dnsConfig:
    nameservers:
      - 8.8.8.8
  #域名映射
  hostAliases:
    - ip: 192.168.56.80
      hostnames:
        - "foo.local"
        - "bar.local"
  containers:
    - name: nginx
      image: nginx:1.17.1
      imagePullPolicy: IfNotPresent
      ports:
        - name: nginx-port
          containerPort: 80
          protocol: TCP
          hostPort: 8080 # 如果使用 hostNetwork 则这里不生效
