apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeimooc-admin
  namespace: kubeimooc-system
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: kubeimooc-role
#  namespace: kubeimooc-system
#rules:
#  - apiGroups:
#      - ""
#    resources:
#      - pods
#    verbs:
#      - get
#      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeimooc-admin-crb
  namespace: kubeimooc-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - name: kubeimooc-admin
    namespace: kubeimooc-system
    kind: ServiceAccount